// <auto-generated />
using System;
using Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HomeDbContext))]
    partial class HomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entitys.Home.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<double>("Arena")
                        .HasColumnType("double precision");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfRoom")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domain.Entitys.Home.HomeRent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<double>("Arena")
                        .HasColumnType("double precision");

                    b.Property<string>("DayMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HomeOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfRoom")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomeRents");
                });

            modelBuilder.Entity("Domain.Entitys.Home.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<double>("Arena")
                        .HasColumnType("double precision");

                    b.Property<string>("DayMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfRoom")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Domain.Entitys.Home.Services.HomeBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<string>("FormatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TheEmployerAndEmployee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomeBuilds");
                });

            modelBuilder.Entity("Domain.Entitys.Home.Services.HomeRepair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TheEmployerAndEmployee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomeRepairs");
                });

            modelBuilder.Entity("Domain.Entitys.Home.Services.TechnicalServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TheEmployerAndEmployee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TechnicalServices");
                });

            modelBuilder.Entity("Domain.Entitys.Home.SpareParts.ConstructionMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SizeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConstructionMaterials");
                });

            modelBuilder.Entity("Domain.Entitys.Home.SpareParts.HomeAppliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<string>("BrendType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeApplianceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberOfProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("HomeAppliances");
                });

            modelBuilder.Entity("Domain.Entitys.Home.SpareParts.HomeEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressDistrict")
                        .HasColumnType("integer");

                    b.Property<int>("AddressProvince")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformationUniversal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoneyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberOfProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RawMaterialType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomeEquipment");
                });
#pragma warning restore 612, 618
        }
    }
}
